app/models.py
from sqlalchemy.orm import backref
from . import db, login_manager
from flask_login import UserMixin
from datetime import datetime



@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(db.Model, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer(), primary_key = True)
    username = db.Column(db.String(20), nullable = False)
    email = db.Column(db.String(), nullable = False)
    password =db.Column(db.String(80))
    bio = db.Column(db.String(255), default = 'You bio  is empty')
    image_url = db.Column(db.String(), default =' profile.jgp')
    posts = db.relationship('Posts', backref = 'author', lazy = 'dynamic')
    comments = db.relationship('Comments', backref = 'commentator', lazy = 'dynamic')


class Posts (db.Model):
    __tablename__ = 'pitches'
    id = db.Column(db.Integer(), primary_key = True)
    title = db.Column(db.String(20), nullable = False)
    content = db.Column(db.String(255))
    timestamp = db.Column(db.DateTime(), index=True, default=datetime.utcnow)
    user_id = db.Column(db.Integer(), db.ForeignKey('users.id'))




    # @property
    # def password(self):
    #     raise ValidationError('Password cannot be read')


    # @password.setter
    # def password(self,password):
    #         self.password_hash = generate_password_hash(password)


    # def verify_password(self,password):
    #     check_password_hash(self.password_hash, password)
     

    def __repr__(self):
        return '<User %r>' % self.username

class Comments(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer(), primary_key = True)
    username = db.Column(db.String(20), nullable = False)
    comment = db.Column(db.String(255), nullable = False)
    user_id = db.Column(db.Integer(), db.ForeignKey('users.id'))
    

app/main/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileField
from  wtforms import SubmitField, StringField, TextAreaField
from wtforms.validators import DataRequired, ValidationError
from ..models import User
from flask_login import current_user



class WriteForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    story = StringField('Write a story',validators=[DataRequired()])
    submit = SubmitField('Publish')


class EditProfile(FlaskForm):
    user = StringField('Username')
    bio = TextAreaField('Add more about you')
    picture_upload = FileField('Upload profile picture', validators = [FileAllowed(['jpg','png','jpeg'])])
    submit = SubmitField('Update')


    def username(self, field):
       
        if field.data != current_user.user :
           user = User.query.filter_by(username = field.data).all()
           if user:
            raise ValidationError('Username exists. Please choose another username')

app/__init__.py
from flask import Flask
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_bootstrap import Bootstrap
from flask_mail import Mail
# from flask_uploads import configure_uploads, IMAGES, UploadSet

db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
bootstrap =Bootstrap()
mail = Mail()
# photos = UploadSet('photos', IMAGES)

def create_app(config_name):

    app = Flask(__name__)
    app.config.from_object(config_options[config_name])
    

    # #configure requests
    # from .requests import configure_requests
    # configure_requests(app)

    #registering blueprints

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix = '/auth')

    #initializinga extensions

    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)
    bootstrap.init_app(app)
    mail.init_app(app)
     # configure UploadSet
    # configure_uploads(app,photos)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import forms,views

app/main/views.py
from flask_login import login_required, current_user
from app import main, db
from flask import render_template,redirect,url_for, flash, abort
from app.requests import get_quotes
from . import main
from .forms import EditProfile, WriteForm
from ..models import User, Posts
import secrets
import os



@main.route('/') 
def index():
    # quotes = get_quotes()
    posts = Posts.query.all()

    # blogs = [
    #     {
    #         'title':
    #     }
    # ]

    return render_template('index.html', posts = posts)


@main.route('/publish/new', methods = ['GET','POST'])
@login_required
def write():
    form = WriteForm()
    if form.validate_on_submit():
        post = Posts(title = form.title.data, content = form.story.data, author = current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!','success')
        return redirect(url_for('main.account'))
    posts = Posts.query.all()
    return render_template('write.html', form = form, posts = posts)

@main.route('/account')
@login_required
def account():
    quotes = get_quotes()
    posts = Posts.query.all()
    image = current_user.image_url
    return render_template('account.html', quotes= quotes, posts = posts, image=image)

def save_picture(form_picture):
    random_hex = secrets.token_hex(8)
    _, fn_ext = os.path.splitext(form_picture.filename)
    picture_fn = fn_ext
    pic_full_path = os.path.join('app/static/images', 'profile.jpg')
    form_picture.save(pic_full_path)
    return picture_fn


@main.route('/profile', methods = ['GET','POST'])
def profile():
    form = EditProfile()
    image_file = url_for('static', filename = 'images/'+ 'profile.jpg')
    posts = Posts.query.all()
    user = User.query.filter_by(username = current_user.username).first
    if form.validate_on_submit():
        if form.picture_upload.data:
            picture_file = save_picture(form.picture_upload.data)
            current_user.image_url = picture_file
        current_user.username = form.user.data
        current_user.bio = form.bio.data
        db.session.commit()
        flash('Acount updated successfully', 'success')

    form.user.data = current_user.username
    form.bio.data = current_user.bio

    return render_template('userprof.html', form = form, image = image_file,user = user, posts = posts)


@main.route('/post/<int:post_id>')
def post(post_id):
    posts = Posts.query.get_or_404(post_id)
    return render_template('post.html', posts = posts)


@main.route('/post/<int:post_id>/delete')
def delete(post_id):
    post = Posts.query.get_or_404(post_id)
    db.session.delete(post)
    db.session.commit()
    return redirect(url_for('main.account') )

app/templates/account.html
{% extends 'layout.html' %}




{% block content %}
{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-success alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
 {{message}}
</div>
{% endfor %}
{% endif%}
{% endwith %}
<div class="container">
  <div class="row">
    <div class="col-md-7">
      <h1>Hello {{current_user.username}},</h1>
        <h4>Quote of the day</h4>
      <p>'{{quotes.quote}}'</p>
      <small>By:{{quotes.author}}</small>
      <hr>
      <h1 class = 'text-center'>Topics For you</h1>
      {% for post in posts %}
      <h3><a href="{{url_for('main.post', post_id =post.id ) }}">{{post.title}}</a></h3>
      <p>{{post.content}}</p>
      <small>{{post.author.username}}...</small>
      <small>from your network</small><br>
      <small>{{post.timestamp}}</small>
      <p><a href="">Comment</a></p>
      
      <hr>

      {% endfor %}
    </div>
    <div class="col-md-5">
      <hr>
      <div class="foot">

      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/index.html
{% extends 'layout.html'%}
{% block css%}
<link rel="stylesheet" href="{{url_for('static',filename='css/home.css')}}">
{% endblock %}  
  {% block content %}
  <section id = "home">
    <div class="container">
      <div class="row">
        <div class="col-md-7">
          <h1>
            SHREDEDD is a place to read, write and network
          </h1>
          <p>
            It's easy and free to post your thinking and connect with millions of readers.
          </p>
         <a href="{{url_for('main.write')}}"> <button class = 'btn btn-write'>Start Writing </button></a>
  
        </div>
        <div class="col-md-5">
          <img src="{{url_for('static', filename='/images/hero.jpg')}}" alt="">
        </div>
      </div>
    </div>
  </section>
  <hr>

  <section id = "home">
    <div class="container">
      <div class="row">
        <div class="col-md-7">
          <h1 class = "text-center">
           Read Below 
          </h1>
          <div class="content">
            <div class="head">
              <h3>Recommended For You</h3>
              {% for post in posts %}
              <h2>{{post.title}}</h2>
              <p>{{post.content}}</p>
              <small>{{post.author.username}}</small>
              <div>
                <small>{{post.timestamp.strftime("%m/%d/%Y")}}</small>
              </div>
              
              <hr>
              {% endfor %}
            </div>
          </div>
  
        </div>
        <div class="col-md-5">
         <h3 class = "text-center"> 
           Discover
         </h3>
         <div class="cat-holder">
          <div class = 'cats'>
            <div class = 'one' >
              <a href="{{url_for('main.account')}}">Programming</a>
             </div>
             <div  class = 'one'>
               <a href="{{url_for('main.account')}}">JavaScript</a>
              </div>
              <div  class = 'one'>
               <a href="{{url_for('main.account')}}">Branding</a>
              </div>
              <div  class = 'one'>
               <a href="{{url_for('main.account')}}">Science</a>
              </div>
              <div  class = 'one'>
               <a href="{{url_for('main.account')}}">Data Structures</a>
              </div>
              <div  class = 'one'>
               <a href="{{url_for('main.account')}}">Politics</a>
              </div>
              <div  class = 'one'>
               <a href="{{url_for('main.account')}}">Data Science</a>
              </div>
              <div  class = 'one'>
               <a href="{{url_for('main.account')}}">Python</a>
              </div>
            </div> 
         </div>
        
         <div class="topics">
          <a href="">see all topics</a>
          
        </div>
        
         <hr>
         <div class="about">
          <div class = 'cats'>
            <div>
              <a href="#home">Help</a>
             </div>
             <div>
               <a href="#home">Wite</a>
              </div>
              <div>
               <a href="#home">More</a>
              </div>
              <div>
               <a href="#home">careers</a>
              </div>
              <div>
               <a href="#home">Privacy</a>
              </div>
              <div>
               <a href="#home">Blog</a>
              </div>
              <div>
               <a href="#home">terms</a>
              </div>
              <div>
               <a href="#home">About</a>
              </div>
            </div> 
         </div>
        </div>
      </div>
    </div>
  </section>
  {% endblock %}
</body>
</htmle

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Font-awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
    integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
  <!-- favicon  -->
  <!-- Google fonts -->
  <title>Awadh blog</title>
  <!-- css -->
  
  {% block css%}
  {% endblock %}
  
  {% extends 'bootstrap/base.html' %}
  {% block title %}
  
  {% endblock %}
</head>

<body>
  {% block navbar %}
  <div class="navbar navbar-inverse" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{{url_for('main.index')}}"><i class="fas fa-book-reader"></i> SHREDEDD</a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav pull-right">
          
          {% if current_user.is_authenticated %}
          <li><a href="{{url_for('main.account')}}">Account</a></li>
         <li><a href="{{url_for('main.write')}}">Write</a></li>
         <li><a href="{{url_for('main.profile')}}"> <i class="fas fa-user-alt"></i> Profile</a></li>
        <li><a href= "{{url_for('auth.logout')}}"><i class="fas fa-sign-out-alt"></i> Logout</a></li> 
         

          {% else %}
          <li><a href="">Our Story</a></li>
          <li class=""><a href="{{url_for('auth.login')}}"><i class="fas fa-sign-in-alt"></i> Login</a></li>
          <li><a href="{{url_for('auth.login')}}">Write</a></li>
          <li class = 'ml-2'><button class = "btn btn-nav ml-2"><a href="{{url_for('auth.register')}}">Get Started</a></button></li>
          {% endif %}

          

        </ul>
      </div>
    </div>
  </div>
  {% endblock %}

  {% block content %}
  {% endblock %}

 

 
</body>

</html>

app/templates/login.html
{% extends 'layout.html' %}
{% block css %}
<link rel="stylesheet" href="{{url_for('static',filename = 'css/auth.css')}}">
{% endblock %}

{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}

<div class="container">
  
  <div class="holder">
    
    <div class="cont-card">
            
      {% with messages = get_flashed_messages() %}
      {% if messages %}
      {% for message in messages %}
      <div class="alert alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      {{message}}
      </div>
      {% endfor %}
      {% endif%}
      {% endwith %}
      <h1 class = 'text-center'>Login</h1>
      {{wtf.quick_form(form)}}
      <div class="don">
        <div class="sign">
          <p> Don't have an account?</p>
        </div>
        <div class="lnk">
          <a href="{{url_for('auth.register')}}">sign Up</a>
        </div>
      </div>
    </div>
    
  </div>
  
</div>
  
{% endblock %}

app/templates/post.html
{% extends 'layout.html' %}
{% block content %}


<div class="container">
  <div class="content">
    <div class="head">
      <h2>{{posts.title}}</h2>
      <p>{{posts.content}}</p>
      <small>{{posts.author.username}}</small>
      <div>
        <small>{{post.timestamp.strftime("%m/%d/%Y")}}</small>
      </div>
      <div>
        <a href="{{url_for('main.delete', post_id = posts.id)}}"><button type = 'button'class = "btn btn-large btn-danger">Delete</button></a>
      </div>
     
      <hr>
</div>


    {% endblock %}

app/templates/register.html
{% extends 'layout.html' %}
{% block css %}
<link rel="stylesheet" href="{{url_for('static',filename = 'css/auth.css')}}">
{% endblock %}

{% import 'bootstrap/wtf.html' as wtf %}


{% block content %}
<div>
  <h1 class = 'text-center'>Sign Up</h1>
</div>
<div class="container">
  <div class="holder">
    <div class="cont-card">
      {{wtf.quick_form(form)}}
    </div>
    
  </div>
  
</div>
  
{% endblock %}

app/templates/userprof.html
{% extends 'layout.html' %}
{% block css %}
<link rel="stylesheet" href="{{url_for('static', filename = 'css/edit.css')}}">
{% endblock %}

{% import 'bootstrap/wtf.html' as wtf%}



{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-7">
      <div class="profile">
        <div class = "image">
          <img class = "rounded-circle" src="{{image}}" alt="">
          </div>
          <div>
            <h1>{{current_user.username}}</h1>
            <p class="mail">{{current_user.email}}</p>
            <small>{{current_user.bio}}</small>
          </div>
      </div>
      
      <div class="edit">  
        <h1>
          Edit your profile
        </h1>
        <hr>
        <div>
          {{wtf.quick_form(form)}}
        </div>
      </div>
    </div>
    <div class="col-md-5">
      <h1 class = "text-center">My stories</h1>
      <hr>
      {%  for posts in posts %}
      <p>{{posts.author.posts}}</p>
      {% endfor %}
      
    </div>
  </div>
 
 
</div>

 {% endblock %}

app/templates/write.html
{% extends 'layout.html' %}

{% import 'bootstrap/wtf.html' as wtf %}


{% block content %}
<div class="container">
  <div>
    <h1>Draft and Speak Your Mind</h1>
  </div>
  {{wtf.quick_form(form)}}
</div>


{% endblock %}